services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=spirit
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d spirit -U pguser"]
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
  migrate:
    build: .
    env_file:
      - .env
    profiles:
      - migrate
    depends_on:
      - web
    restart: no
    entrypoint: ["/app/spirit", "migrate", "up"]